const uart=@import("../console/uart.zig");
const vm=@import("vm.zig"); const vcpu=@import("vcpu.zig"); const ctx=@import("guest_context.zig"); const hgatp=@import("hgatp_candidate.zig"); const plan=@import("stage2_activation_plan.zig");
pub const GuestEntryFrameState=enum{empty,built,validated,rejected};
pub const GuestEntryFrameBlocker=enum{none,empty,not_built,activation_plan_missing,hgatp_missing,guest_context_missing,register_corrupt,pc_changed,sp_changed,a0_changed,a1_changed,a2_changed,guest_entered_forbidden,instruction_executed_forbidden,trap_return_executed_forbidden,hgatp_written_forbidden,active_stage2_forbidden,checksum_zero};
pub const Result=enum{ok,rejected};
pub const GuestEntryRegisterImage=struct{pc:usize,sp:usize,a0:usize,a1:usize,a2:usize,status_metadata:usize,privilege_metadata:usize,trap_vector_metadata:usize,hgatp_checksum:usize,activation_plan_checksum:usize,context_checksum:usize,checksum:usize};
pub const GuestEntrySourceSummary=struct{hgatp_checksum:usize,hgatp_value:usize,activation_plan_checksum:usize,activation_plan_next:usize,guest_context_source:usize,guest_context_state:usize};
pub const GuestEntryFrame=struct{owner_vm_id:vm.VmId,owner_vcpu_id:vcpu.VcpuId,state:GuestEntryFrameState,guest_pc:usize,guest_sp:usize,guest_a0:usize,guest_a1:usize,guest_a2:usize,argument_metadata:usize,privilege_metadata:usize,trap_vector_metadata:usize,status_metadata:usize,register_image:GuestEntryRegisterImage,sources:GuestEntrySourceSummary,execution_ready:bool,first_blocker:GuestEntryFrameBlocker,blocker_count:usize,checksum:usize,build_count:usize,validate_count:usize,reject_count:usize,reset_count:usize,guest_entered:bool,guest_instruction_executed:bool,trap_return_executed:bool,hgatp_written:bool,active_stage2:bool};
var obj:GuestEntryFrame=undefined; var inited=false;
pub fn init(owner:vm.VmId,vc:vcpu.VcpuId)void{obj=empty(owner,vc,0);inited=true;} pub fn object()*const GuestEntryFrame{return mut();} fn mut()*GuestEntryFrame{if(!inited)init(vm.object().id,vcpu.object().id);return &obj;}
fn empty(owner:vm.VmId,vc:vcpu.VcpuId,resets:usize)GuestEntryFrame{return .{.owner_vm_id=owner,.owner_vcpu_id=vc,.state=.empty,.guest_pc=0,.guest_sp=0,.guest_a0=0,.guest_a1=0,.guest_a2=0,.argument_metadata=0,.privilege_metadata=0,.trap_vector_metadata=0,.status_metadata=0,.register_image=.{.pc=0,.sp=0,.a0=0,.a1=0,.a2=0,.status_metadata=0,.privilege_metadata=0,.trap_vector_metadata=0,.hgatp_checksum=0,.activation_plan_checksum=0,.context_checksum=0,.checksum=0},.sources=.{.hgatp_checksum=0,.hgatp_value=0,.activation_plan_checksum=0,.activation_plan_next=0,.guest_context_source=0,.guest_context_state=0},.execution_ready=false,.first_blocker=.empty,.blocker_count=1,.checksum=0,.build_count=0,.validate_count=0,.reject_count=0,.reset_count=resets,.guest_entered=false,.guest_instruction_executed=false,.trap_return_executed=false,.hgatp_written=false,.active_stage2=false};}
pub fn reset()void{const f=mut();obj=empty(f.owner_vm_id,f.owner_vcpu_id,f.reset_count+1);inited=true;}
fn mix(a:usize,b:usize)usize{return (a ^% (b+%0x9e3779b97f4a7c15))*%0xbf58476d1ce4e5b9;} fn nz(x:usize)usize{return if(x==0)1 else x;}
fn contextChecksum(c:anytype)usize{var x:usize=0x6326; x=mix(x,c.guest_pc);x=mix(x,c.guest_sp);x=mix(x,c.a0);x=mix(x,c.a1);x=mix(x,c.a2);x=mix(x,c.status_metadata);x=mix(x,c.privilege_metadata);return nz(x);} 
fn regChecksum(r:GuestEntryRegisterImage)usize{var x:usize=0x72656726; inline for(.{r.pc,r.sp,r.a0,r.a1,r.a2,r.status_metadata,r.privilege_metadata,r.trap_vector_metadata,r.hgatp_checksum,r.activation_plan_checksum,r.context_checksum})|v| x=mix(x,v); return nz(x);} 
fn frameChecksum(f:GuestEntryFrame)usize{var x:usize=0x6672616d653236; inline for(.{f.owner_vm_id,f.owner_vcpu_id,f.guest_pc,f.guest_sp,f.guest_a0,f.guest_a1,f.guest_a2,f.argument_metadata,f.privilege_metadata,f.trap_vector_metadata,f.status_metadata,f.register_image.checksum,f.sources.hgatp_checksum,f.sources.hgatp_value,f.sources.activation_plan_checksum,f.sources.activation_plan_next,f.sources.guest_context_source})|v| x=mix(x,v); return nz(x);} 
pub fn build()Result{ensurePrereq(); const f=mut(); f.build_count+=1; f.state=.built; f.owner_vm_id=vm.object().id; f.owner_vcpu_id=vcpu.object().id; const c=ctx.object(); const h=hgatp.object(); const p=plan.object(); f.guest_pc=c.guest_pc;f.guest_sp=c.guest_sp;f.guest_a0=c.a0;f.guest_a1=c.a1;f.guest_a2=c.a2;f.argument_metadata=3;f.privilege_metadata=c.privilege_metadata;f.trap_vector_metadata=c.kernel_entry_gpa ^ c.fdt_gpa;f.status_metadata=c.status_metadata; const cc=contextChecksum(c.*); f.sources=.{.hgatp_checksum=h.checksum,.hgatp_value=h.value,.activation_plan_checksum=p.checksum,.activation_plan_next=@intFromEnum(p.next),.guest_context_source=cc,.guest_context_state=@intFromEnum(c.state)}; f.register_image=.{.pc=f.guest_pc,.sp=f.guest_sp,.a0=f.guest_a0,.a1=f.guest_a1,.a2=f.guest_a2,.status_metadata=f.status_metadata,.privilege_metadata=f.privilege_metadata,.trap_vector_metadata=f.trap_vector_metadata,.hgatp_checksum=h.checksum,.activation_plan_checksum=p.checksum,.context_checksum=cc,.checksum=0}; f.register_image.checksum=regChecksum(f.register_image); f.checksum=frameChecksum(f.*); return validate();}
fn ensurePrereq()void{ if(ctx.object().state!=.validated) _=ctx.prepare(); if(hgatp.object().state!=.validated) {_=hgatp.build(); _=hgatp.validate();} if(plan.object().state!=.validated) {_=plan.build(); _=plan.validate();}}
fn reject(e:GuestEntryFrameBlocker)Result{const f=mut();f.reject_count+=1;f.state=.rejected;f.execution_ready=false;f.first_blocker=e;f.blocker_count=1;return .rejected;}
fn firstBlocker()GuestEntryFrameBlocker{const f=object(); if(f.state==.empty)return .empty; if(f.state!=.built and f.state!=.validated and f.state!=.rejected)return .not_built; if(plan.object().state!=.validated or plan.object().checksum==0)return .activation_plan_missing; if(hgatp.object().state!=.validated or hgatp.object().checksum==0)return .hgatp_missing; if(ctx.object().state!=.validated)return .guest_context_missing; if(f.guest_entered)return .guest_entered_forbidden; if(f.guest_instruction_executed)return .instruction_executed_forbidden; if(f.trap_return_executed)return .trap_return_executed_forbidden; if(f.hgatp_written)return .hgatp_written_forbidden; if(f.active_stage2)return .active_stage2_forbidden; if(f.guest_pc!=f.register_image.pc)return .pc_changed; if(f.guest_sp!=f.register_image.sp)return .sp_changed; if(f.guest_a0!=f.register_image.a0)return .a0_changed; if(f.guest_a1!=f.register_image.a1)return .a1_changed; if(f.guest_a2!=f.register_image.a2)return .a2_changed; if(f.register_image.checksum!=regChecksum(f.register_image))return .register_corrupt; if(f.checksum==0)return .checksum_zero; return .none;}
pub fn validate()Result{const f=mut();f.validate_count+=1;const e=firstBlocker();if(e!=.none)return reject(e);f.state=.validated;f.execution_ready=true;f.first_blocker=.none;f.blocker_count=0;return .ok;}
pub fn mutatePc()usize{_=build();mut().guest_pc +%= 4;mut().register_image.pc=mut().guest_pc;mut().register_image.checksum=regChecksum(mut().register_image);mut().checksum=frameChecksum(mut().*);return mut().checksum;} pub fn mutateSp()usize{_=build();mut().guest_sp +%= 16;mut().register_image.sp=mut().guest_sp;mut().register_image.checksum=regChecksum(mut().register_image);mut().checksum=frameChecksum(mut().*);return mut().checksum;} pub fn mutateArgs()usize{_=build();mut().guest_a0 +%= 1;mut().guest_a1 +%= 2;mut().guest_a2 +%= 3;mut().register_image.a0=mut().guest_a0;mut().register_image.a1=mut().guest_a1;mut().register_image.a2=mut().guest_a2;mut().register_image.checksum=regChecksum(mut().register_image);mut().checksum=frameChecksum(mut().*);return mut().checksum;}
pub fn corruptRegister()Result{_=build();mut().register_image.a0 +%= 99;return validate();} pub fn missingActivationPlan()Result{reset(); return reject(.activation_plan_missing);} pub fn missingContext()Result{reset(); return reject(.guest_context_missing);} pub fn markGuestEntered()Result{_=build();mut().guest_entered = true;return validate();} pub fn markInstruction()Result{_=build();mut().guest_instruction_executed = true;return validate();} pub fn markTrapReturn()Result{_=build();mut().trap_return_executed = true;return validate();} pub fn markHgatpWritten()Result{_=build();mut().hgatp_written = true;return validate();} pub fn markActiveStage2()Result{_=build();mut().active_stage2 = true;return validate();}
fn bn(e:GuestEntryFrameBlocker)[]const u8{return switch(e){.none=>"none",.empty=>"empty",.not_built=>"not-built",.activation_plan_missing=>"activation-plan-missing",.hgatp_missing=>"hgatp-missing",.guest_context_missing=>"guest-context-missing",.register_corrupt=>"register-corrupt",.pc_changed=>"pc-changed",.sp_changed=>"sp-changed",.a0_changed=>"a0-changed",.a1_changed=>"a1-changed",.a2_changed=>"a2-changed",.guest_entered_forbidden=>"guest-entered-forbidden",.instruction_executed_forbidden=>"instruction-executed-forbidden",.trap_return_executed_forbidden=>"trap-return-executed-forbidden",.hgatp_written_forbidden=>"hgatp-written-forbidden",.active_stage2_forbidden=>"active-stage2-forbidden",.checksum_zero=>"checksum-zero"};} fn rn(r:Result)[]const u8{return if(r==.ok)"ok" else "rejected";}
fn nonclaims()void{uart.write("hv: guest_entered=false\r\nhv: guest_instruction_executed=false\r\nhv: trap_return_executed=false\r\nhv: hgatp_written=false\r\nhv: active_stage2=false\r\n");}
fn summary()void{const f=object();uart.write("hv: guest_entry_frame.state=");uart.write(@tagName(f.state));uart.write("\r\nhv: guest_entry_frame.checksum=");uart.writeHex(f.checksum);uart.write("\r\nhv: guest_entry_frame.register_checksum=");uart.writeHex(f.register_image.checksum);uart.write("\r\nhv: guest_entry_frame.consumed_hgatp_checksum=");uart.writeHex(f.sources.hgatp_checksum);uart.write("\r\nhv: guest_entry_frame.consumed_activation_plan_checksum=");uart.writeHex(f.sources.activation_plan_checksum);uart.write("\r\nhv: guest_entry_frame.consumed_context_checksum=");uart.writeHex(f.sources.guest_context_source);uart.write("\r\nhv: guest_entry_frame.build_count=");uart.writeDec(f.build_count);uart.write("\r\nhv: guest_entry_frame.validate_count=");uart.writeDec(f.validate_count);uart.write("\r\nhv: guest_entry_frame.reject_count=");uart.writeDec(f.reject_count);uart.write("\r\n");}
pub fn printStatusCommand()void{summary();printBlockersCommand();nonclaims();} pub fn printBuildCommand()void{const r=build();uart.write("hv: guest_entry_frame.build_result=");uart.write(rn(r));uart.write("\r\n");summary();nonclaims();} pub fn printValidateCommand()void{const r=validate();uart.write("hv: guest_entry_frame.validate_result=");uart.write(rn(r));uart.write("\r\n");summary();printBlockersCommand();nonclaims();} pub fn printBlockersCommand()void{const f=object();uart.write("hv: guest_entry_frame.blocker_count=");uart.writeDec(f.blocker_count);uart.write("\r\nhv: guest_entry_frame.blocker=");uart.write(bn(f.first_blocker));uart.write("\r\n");} pub fn printFieldsCommand()void{summary();nonclaims();} pub fn printRegistersCommand()void{const r=object().register_image;uart.write("hv: guest_entry_frame.registers=structured\r\nhv: guest_entry_frame.pc=");uart.writeHex(r.pc);uart.write("\r\nhv: guest_entry_frame.sp=");uart.writeHex(r.sp);uart.write("\r\nhv: guest_entry_frame.a0=");uart.writeHex(r.a0);uart.write("\r\nhv: guest_entry_frame.a1=");uart.writeHex(r.a1);uart.write("\r\nhv: guest_entry_frame.a2=");uart.writeHex(r.a2);uart.write("\r\n");nonclaims();} pub fn printChecksumCommand()void{uart.write("hv: guest_entry_frame.checksum=");uart.writeHex(object().checksum);uart.write("\r\n");} pub fn printResetCommand()void{reset();uart.write("hv: guest_entry_frame.reset_result=ok\r\n");summary();nonclaims();}
pub fn printTest(label:[]const u8,r:Result)void{uart.write("hv: guest_entry_frame.");uart.write(label);uart.write("=");uart.write(rn(r));uart.write("\r\n");printBlockersCommand();summary();nonclaims();}
