const uart = @import("../console/uart.zig");
const vm = @import("vm.zig");
const vcpu = @import("vcpu.zig");
const hgatp_candidate = @import("hgatp_candidate.zig");
const second_stage = @import("second_stage.zig");
const stage2_table = @import("stage2_table.zig");
const h_extension = @import("h_extension.zig");

pub const HgatpActivationReadinessState = enum { empty, observed, ready, rejected };
pub const HgatpActivationBlocker = enum { none, empty_readiness, missing_hgatp_candidate, invalid_hgatp_candidate, missing_stage2_metadata, missing_stage2_table, missing_h_extension_discovery, missing_csr_safety, source_mutated, hgatp_write_attempted, active_stage2_forbidden };
pub const HgatpActivationNextAction = enum { none, build_hgatp_candidate_externally, validate_hgatp_candidate_externally, build_stage2_metadata_externally, build_stage2_table_externally, discover_h_extension_externally, establish_csr_safety_externally, investigate_source_mutation, stop_hgatp_write_observed, stop_active_stage2_observed, future_guarded_write_planning };
pub const HgatpActivationSourceFingerprint = struct { hgatp_state: usize, hgatp_ready: bool, hgatp_value: usize, hgatp_checksum: usize, hgatp_build_count: usize, hgatp_validate_count: usize, hgatp_reject_count: usize, second_stage_state: usize, second_stage_mapping_validated: bool, second_stage_active: bool, stage2_table_state: usize, stage2_table_entry_count: usize, stage2_table_active: bool, h_extension_state: usize, h_extension_unsafe_forbidden: bool, h_extension_hgatp_write_status: usize, h_extension_blocked_count: usize, h_extension_readable_count: usize, vm_id: vm.VmId, vcpu_id: vcpu.VcpuId, checksum: usize };
pub const HgatpActivationSourceSummary = struct { hgatp_candidate_present: bool, hgatp_candidate_valid: bool, hgatp_candidate_checksum: usize, hgatp_candidate_value: usize, stage2_metadata_present: bool, stage2_table_present: bool, h_extension_discovery_present: bool, csr_safety_present: bool, hgatp_write_attempted: bool, active_stage2: bool };
pub const HgatpActivationReadiness = struct { owner_vm_id: vm.VmId, owner_vcpu_id: vcpu.VcpuId, hgatp_candidate_present: bool, hgatp_candidate_valid: bool, hgatp_candidate_checksum: usize, hgatp_candidate_value: usize, stage2_metadata_present: bool, stage2_table_present: bool, h_extension_discovery_present: bool, csr_safety_present: bool, source_fingerprint_before: HgatpActivationSourceFingerprint, source_fingerprint_after: HgatpActivationSourceFingerprint, source_fingerprint_unchanged: bool, hgatp_write_allowed: bool, hgatp_write_attempted: bool, active_stage2: bool, ready_for_future_guarded_write: bool, next_action: HgatpActivationNextAction, blocker: HgatpActivationBlocker, blocker_count: usize, checksum: usize, state: HgatpActivationReadinessState, ready: bool, last_error: HgatpActivationBlocker, build_count: usize, validate_count: usize, reject_count: usize, reset_count: usize };

var obj: HgatpActivationReadiness = undefined;
var initialized = false;

pub fn init(owner: vm.VmId, owner_vcpu: vcpu.VcpuId) void { obj = empty(owner, owner_vcpu, 0); initialized = true; }
pub fn object() *const HgatpActivationReadiness { return mutable(); }
fn mutable() *HgatpActivationReadiness { if (!initialized) init(vm.object().id, vcpu.object().id); return &obj; }
fn emptyFp() HgatpActivationSourceFingerprint { return .{ .hgatp_state=0,.hgatp_ready=false,.hgatp_value=0,.hgatp_checksum=0,.hgatp_build_count=0,.hgatp_validate_count=0,.hgatp_reject_count=0,.second_stage_state=0,.second_stage_mapping_validated=false,.second_stage_active=false,.stage2_table_state=0,.stage2_table_entry_count=0,.stage2_table_active=false,.h_extension_state=0,.h_extension_unsafe_forbidden=false,.h_extension_hgatp_write_status=0,.h_extension_blocked_count=0,.h_extension_readable_count=0,.vm_id=0,.vcpu_id=0,.checksum=0 }; }
fn empty(owner: vm.VmId, owner_vcpu: vcpu.VcpuId, resets: usize) HgatpActivationReadiness { return .{ .owner_vm_id=owner,.owner_vcpu_id=owner_vcpu,.hgatp_candidate_present=false,.hgatp_candidate_valid=false,.hgatp_candidate_checksum=0,.hgatp_candidate_value=0,.stage2_metadata_present=false,.stage2_table_present=false,.h_extension_discovery_present=false,.csr_safety_present=false,.source_fingerprint_before=emptyFp(),.source_fingerprint_after=emptyFp(),.source_fingerprint_unchanged=false,.hgatp_write_allowed=false,.hgatp_write_attempted=false,.active_stage2=false,.ready_for_future_guarded_write=false,.next_action=.none,.blocker=.none,.blocker_count=0,.checksum=0,.state=.empty,.ready=false,.last_error=.none,.build_count=0,.validate_count=0,.reject_count=0,.reset_count=resets }; }
pub fn reset() void { const r = mutable().reset_count + 1; obj = empty(vm.object().id, vcpu.object().id, r); initialized = true; }
fn tag(e: anytype) usize { return @intFromEnum(e); }
fn mix(x: usize, y: usize) usize { return (x ^ y) *% 0x9e37_79b9_7f4a_7c15; }
fn fpChecksum(f: HgatpActivationSourceFingerprint) usize { var x: usize = 0x26; x=mix(x,f.hgatp_state); x=mix(x,if (f.hgatp_ready)1 else 0); x=mix(x,f.hgatp_value); x=mix(x,f.hgatp_checksum); x=mix(x,f.hgatp_build_count); x=mix(x,f.hgatp_validate_count); x=mix(x,f.hgatp_reject_count); x=mix(x,f.second_stage_state); x=mix(x,if (f.second_stage_mapping_validated)1 else 0); x=mix(x,if (f.second_stage_active)1 else 0); x=mix(x,f.stage2_table_state); x=mix(x,f.stage2_table_entry_count); x=mix(x,if (f.stage2_table_active)1 else 0); x=mix(x,f.h_extension_state); x=mix(x,if (f.h_extension_unsafe_forbidden)1 else 0); x=mix(x,f.h_extension_hgatp_write_status); x=mix(x,f.h_extension_blocked_count); x=mix(x,f.h_extension_readable_count); x=mix(x,@intCast(f.vm_id)); x=mix(x,@intCast(f.vcpu_id)); return if (x == 0) 1 else x; }
pub fn readSourceFingerprint() HgatpActivationSourceFingerprint { const c=hgatp_candidate.object(); const ss=second_stage.object(); const tbl=stage2_table.object(); const he=h_extension.object(); var f=HgatpActivationSourceFingerprint{ .hgatp_state=tag(c.state),.hgatp_ready=c.ready,.hgatp_value=c.candidate_value,.hgatp_checksum=c.checksum,.hgatp_build_count=c.build_count,.hgatp_validate_count=c.validate_count,.hgatp_reject_count=c.reject_count,.second_stage_state=tag(ss.state),.second_stage_mapping_validated=ss.mapping.validated,.second_stage_active=ss.mapping.active,.stage2_table_state=tag(tbl.state),.stage2_table_entry_count=tbl.entry_count,.stage2_table_active=tbl.active,.h_extension_state=tag(he.state),.h_extension_unsafe_forbidden=he.unsafe_csr_read_forbidden,.h_extension_hgatp_write_status=tag(he.hgatp_write_status),.h_extension_blocked_count=he.blocked_csr_count,.h_extension_readable_count=he.readable_csr_count,.vm_id=vm.object().id,.vcpu_id=vcpu.object().id,.checksum=0 }; f.checksum=fpChecksum(f); return f; }
fn sameFp(a: HgatpActivationSourceFingerprint, b: HgatpActivationSourceFingerprint) bool { return a.checksum == b.checksum and a.hgatp_state == b.hgatp_state and a.hgatp_value == b.hgatp_value and a.hgatp_checksum == b.hgatp_checksum and a.hgatp_build_count == b.hgatp_build_count and a.hgatp_validate_count == b.hgatp_validate_count and a.hgatp_reject_count == b.hgatp_reject_count and a.second_stage_state == b.second_stage_state and a.stage2_table_state == b.stage2_table_state and a.h_extension_state == b.h_extension_state and a.vm_id == b.vm_id and a.vcpu_id == b.vcpu_id; }
fn summary() HgatpActivationSourceSummary { const c=hgatp_candidate.object(); const ss=second_stage.object(); const tbl=stage2_table.object(); const he=h_extension.object(); return .{ .hgatp_candidate_present=c.state != .empty and c.candidate_value != 0 and c.checksum != 0, .hgatp_candidate_valid=c.state == .validated and c.ready, .hgatp_candidate_checksum=c.checksum, .hgatp_candidate_value=c.candidate_value, .stage2_metadata_present=ss.state == .metadata_ready and ss.mapping.validated and !ss.mapping.active, .stage2_table_present=(tbl.state == .built or tbl.state == .validated) and tbl.entry_count > 0 and !tbl.active, .h_extension_discovery_present=he.state == .discovered or he.state == .validated, .csr_safety_present=he.unsafe_csr_read_forbidden and he.hgatp_write_status == .not_attempted, .hgatp_write_attempted=c.hgatp_write_attempted or he.hgatp_write_status != .not_attempted, .active_stage2=c.active_stage2 or ss.mapping.active or tbl.active }; }
fn firstBlocker(r: HgatpActivationReadiness) HgatpActivationBlocker { if (r.state == .empty) return .empty_readiness; if (!r.source_fingerprint_unchanged) return .source_mutated; if (!r.hgatp_candidate_present) return .missing_hgatp_candidate; if (!r.hgatp_candidate_valid) return .invalid_hgatp_candidate; if (!r.stage2_metadata_present) return .missing_stage2_metadata; if (!r.stage2_table_present) return .missing_stage2_table; if (!r.h_extension_discovery_present) return .missing_h_extension_discovery; if (!r.csr_safety_present) return .missing_csr_safety; if (r.hgatp_write_attempted) return .hgatp_write_attempted; if (r.active_stage2) return .active_stage2_forbidden; return .none; }
fn actionFor(b: HgatpActivationBlocker) HgatpActivationNextAction { return switch(b){ .none=>.future_guarded_write_planning,.empty_readiness=>.none,.missing_hgatp_candidate=>.build_hgatp_candidate_externally,.invalid_hgatp_candidate=>.validate_hgatp_candidate_externally,.missing_stage2_metadata=>.build_stage2_metadata_externally,.missing_stage2_table=>.build_stage2_table_externally,.missing_h_extension_discovery=>.discover_h_extension_externally,.missing_csr_safety=>.establish_csr_safety_externally,.source_mutated=>.investigate_source_mutation,.hgatp_write_attempted=>.stop_hgatp_write_observed,.active_stage2_forbidden=>.stop_active_stage2_observed }; }
fn readinessChecksum(r: HgatpActivationReadiness) usize { var x: usize=0x2626; x=mix(x,r.source_fingerprint_before.checksum); x=mix(x,r.source_fingerprint_after.checksum); x=mix(x,r.hgatp_candidate_checksum); x=mix(x,r.hgatp_candidate_value); x=mix(x,tag(r.blocker)); x=mix(x,tag(r.next_action)); return if (x == 0) 1 else x; }
pub fn build() HgatpActivationBlocker { const r=mutable(); r.build_count += 1; r.owner_vm_id=vm.object().id; r.owner_vcpu_id=vcpu.object().id; r.source_fingerprint_before=readSourceFingerprint(); const s=summary(); r.hgatp_candidate_present=s.hgatp_candidate_present; r.hgatp_candidate_valid=s.hgatp_candidate_valid; r.hgatp_candidate_checksum=s.hgatp_candidate_checksum; r.hgatp_candidate_value=s.hgatp_candidate_value; r.stage2_metadata_present=s.stage2_metadata_present; r.stage2_table_present=s.stage2_table_present; r.h_extension_discovery_present=s.h_extension_discovery_present; r.csr_safety_present=s.csr_safety_present; r.hgatp_write_allowed=false; r.hgatp_write_attempted=s.hgatp_write_attempted; r.active_stage2=s.active_stage2; r.state=.observed; r.source_fingerprint_after=readSourceFingerprint(); r.source_fingerprint_unchanged=sameFp(r.source_fingerprint_before, r.source_fingerprint_after); const b=firstBlocker(r.*); r.blocker=b; r.last_error=b; r.blocker_count=if (b == .none) 0 else 1; r.next_action=actionFor(b); r.ready=b == .none; r.ready_for_future_guarded_write=r.ready; r.state=if (r.ready) .ready else .rejected; if (!r.ready) r.reject_count += 1; r.checksum=readinessChecksum(r.*); return b; }
pub fn validate() HgatpActivationBlocker { const r=mutable(); r.validate_count += 1; const b=firstBlocker(r.*); r.blocker=b; r.last_error=b; r.blocker_count=if (b == .none)0 else 1; r.next_action=actionFor(b); r.ready=b == .none; r.ready_for_future_guarded_write=r.ready; r.state=if (r.ready) .ready else .rejected; if (!r.ready) r.reject_count += 1; r.checksum=readinessChecksum(r.*); return b; }
fn corrupt(kind: HgatpActivationBlocker) HgatpActivationBlocker { _=build(); const r=mutable(); switch(kind){ .missing_hgatp_candidate=>r.hgatp_candidate_present=false,.invalid_hgatp_candidate=>r.hgatp_candidate_valid=false,.missing_stage2_metadata=>r.stage2_metadata_present=false,.missing_stage2_table=>r.stage2_table_present=false,.missing_h_extension_discovery=>r.h_extension_discovery_present=false,.missing_csr_safety=>r.csr_safety_present=false,.hgatp_write_attempted=>r.hgatp_write_attempted=true,.active_stage2_forbidden=>r.active_stage2 = (kind == .active_stage2_forbidden),.source_mutated=>r.source_fingerprint_unchanged=false, else=>{} } return validate(); }
pub fn invariantLifecycle() bool { reset(); const empty_bad=validate()==.empty_readiness; _=build(); const observed=object().build_count==1 and object().checksum != 0; reset(); return empty_bad and observed and object().state == .empty; }
pub fn invariantConsumption() bool { reset(); _=build(); const before=object().hgatp_candidate_checksum; return before == hgatp_candidate.object().checksum; }
pub fn invariantCorruption() bool { return corrupt(.missing_hgatp_candidate)==.missing_hgatp_candidate and corrupt(.invalid_hgatp_candidate)==.invalid_hgatp_candidate and corrupt(.source_mutated)==.source_mutated; }
pub fn printStatusCommand() void { printSummary(); printSources(); printPolicy(); }
pub fn printBuildCommand() void { const b=build(); printResult("build_result", b); printSummary(); printSources(); printPolicy(); }
pub fn printValidateCommand() void { const b=validate(); printResult("validate_result", b); printSummary(); printSources(); printPolicy(); }
pub fn printBlockersCommand() void { _=validate(); printBlockers(); }
pub fn printNextCommand() void { uart.write("hv: hgatp_readiness.next_action="); uart.write(actionName(object().next_action)); uart.write("\r\n"); }
pub fn printChecksumCommand() void { uart.write("hv: hgatp_readiness.checksum="); uart.writeHex(object().checksum); uart.write("\r\n"); }
pub fn printResetCommand() void { reset(); uart.write("hv: hgatp_readiness.reset_result=ok\r\n"); printSummary(); }
pub fn printInvariantLifecycleCommand() void { uart.write("hv: hgatp_readiness.invariant_lifecycle_result="); uart.write(if (invariantLifecycle())"ok" else "rejected"); uart.write("\r\n"); }
pub fn printInvariantConsumptionCommand() void { uart.write("hv: hgatp_readiness.invariant_consumption_result="); uart.write(if (invariantConsumption())"ok" else "rejected"); uart.write("\r\n"); }
pub fn printInvariantCorruptionCommand() void { uart.write("hv: hgatp_readiness.invariant_corruption_result="); uart.write(if (invariantCorruption())"ok" else "rejected"); uart.write("\r\n"); }
pub fn printRequireCandidateTestCommand() void { printResult("require_candidate_test", corrupt(.missing_hgatp_candidate)); printBlockers(); }
pub fn printInvalidCandidateTestCommand() void { printResult("invalid_candidate_test", corrupt(.invalid_hgatp_candidate)); printBlockers(); }
pub fn printRequireStage2TestCommand() void { printResult("require_stage2_test", corrupt(.missing_stage2_metadata)); printBlockers(); }
pub fn printRequireTableTestCommand() void { printResult("require_table_test", corrupt(.missing_stage2_table)); printBlockers(); }
pub fn printRequireHextTestCommand() void { printResult("require_hext_test", corrupt(.missing_h_extension_discovery)); printBlockers(); }
pub fn printRequireCsrSafetyTestCommand() void { printResult("require_csr_safety_test", corrupt(.missing_csr_safety)); printBlockers(); }
pub fn printWriteAttemptTestCommand() void { printResult("write_attempt_test", corrupt(.hgatp_write_attempted)); printBlockers(); }
pub fn printActiveStage2TestCommand() void { printResult("active_stage2_test", corrupt(.active_stage2_forbidden)); printBlockers(); }
pub fn printSourceIntegrityTestCommand() void { printResult("source_integrity_test", corrupt(.source_mutated)); printBlockers(); }
fn printResult(label: []const u8, b: HgatpActivationBlocker) void { uart.write("hv: hgatp_readiness."); uart.write(label); uart.write("="); uart.write(if (b == .none)"ok" else "rejected"); uart.write("\r\n"); uart.write("hv: hgatp_readiness.result_blocker="); uart.write(blockerName(b)); uart.write("\r\n"); }
fn printSummary() void { const r=object(); uart.write("hv: hgatp_readiness=software-only-observer\r\n"); uart.write("hv: hgatp_readiness.state="); uart.write(@tagName(r.state)); uart.write("\r\n"); uart.write("hv: hgatp_readiness.ready="); uart.write(if (r.ready)"true" else "false"); uart.write("\r\n"); uart.write("hv: hgatp_readiness.owner_vm_id="); uart.writeDec(r.owner_vm_id); uart.write("\r\n"); uart.write("hv: hgatp_readiness.owner_vcpu_id="); uart.writeDec(r.owner_vcpu_id); uart.write("\r\n"); uart.write("hv: hgatp_readiness.build_count="); uart.writeDec(r.build_count); uart.write("\r\n"); uart.write("hv: hgatp_readiness.validate_count="); uart.writeDec(r.validate_count); uart.write("\r\n"); uart.write("hv: hgatp_readiness.reject_count="); uart.writeDec(r.reject_count); uart.write("\r\n"); uart.write("hv: hgatp_readiness.reset_count="); uart.writeDec(r.reset_count); uart.write("\r\n"); printBlockers(); uart.write("hv: hgatp_readiness.next_action="); uart.write(actionName(r.next_action)); uart.write("\r\n"); uart.write("hv: hgatp_readiness.checksum="); uart.writeHex(r.checksum); uart.write("\r\n"); }
fn printSources() void { const r=object(); uart.write("hv: hgatp_readiness.hgatp_candidate_present="); uart.write(if (r.hgatp_candidate_present)"yes" else "no"); uart.write("\r\n"); uart.write("hv: hgatp_readiness.hgatp_candidate_valid="); uart.write(if (r.hgatp_candidate_valid)"yes" else "no"); uart.write("\r\n"); uart.write("hv: hgatp_readiness.hgatp_candidate_checksum="); uart.writeHex(r.hgatp_candidate_checksum); uart.write("\r\n"); uart.write("hv: hgatp_readiness.hgatp_candidate_value="); uart.writeHex(r.hgatp_candidate_value); uart.write("\r\n"); uart.write("hv: hgatp_readiness.stage2_metadata_present="); uart.write(if (r.stage2_metadata_present)"yes" else "no"); uart.write("\r\n"); uart.write("hv: hgatp_readiness.stage2_table_present="); uart.write(if (r.stage2_table_present)"yes" else "no"); uart.write("\r\n"); uart.write("hv: hgatp_readiness.h_extension_discovery_present="); uart.write(if (r.h_extension_discovery_present)"yes" else "no"); uart.write("\r\n"); uart.write("hv: hgatp_readiness.csr_safety_present="); uart.write(if (r.csr_safety_present)"yes" else "no"); uart.write("\r\n"); uart.write("hv: hgatp_readiness.source_fingerprint_before="); uart.writeHex(r.source_fingerprint_before.checksum); uart.write("\r\n"); uart.write("hv: hgatp_readiness.source_fingerprint_after="); uart.writeHex(r.source_fingerprint_after.checksum); uart.write("\r\n"); uart.write("hv: hgatp_readiness.source_fingerprint_unchanged="); uart.write(if (r.source_fingerprint_unchanged)"yes" else "no"); uart.write("\r\n"); }
fn printPolicy() void { const r=object(); uart.write("hv: hgatp_readiness.hgatp_write_allowed=no\r\n"); uart.write("hv: hgatp_readiness.hgatp_write_attempted="); uart.write(if (r.hgatp_write_attempted)"yes" else "no"); uart.write("\r\n"); uart.write("hv: hgatp_readiness.active_stage2="); uart.write(if (r.active_stage2)"yes" else "no"); uart.write("\r\n"); uart.write("hv: hgatp_readiness.ready_for_future_guarded_write="); uart.write(if (r.ready_for_future_guarded_write)"yes" else "no"); uart.write("\r\n"); uart.write("hv: hgatp_write=not-attempted\r\n"); uart.write("hv: second_stage_translation=MISSING\r\n"); uart.write("hv: guest_execution=not-supported-yet\r\n"); uart.write("hv: linux_guest=not-supported-yet\r\n"); }
fn printBlockers() void { const r=object(); uart.write("hv: hgatp_readiness.blocker_count="); uart.writeDec(r.blocker_count); uart.write("\r\n"); uart.write("hv: hgatp_readiness.blocker="); uart.write(blockerName(r.blocker)); uart.write("\r\n"); }
fn blockerName(b: HgatpActivationBlocker) []const u8 { return switch(b){ .none=>"none",.empty_readiness=>"empty-readiness",.missing_hgatp_candidate=>"missing-hgatp-candidate",.invalid_hgatp_candidate=>"invalid-hgatp-candidate",.missing_stage2_metadata=>"missing-stage2-metadata",.missing_stage2_table=>"missing-stage2-table",.missing_h_extension_discovery=>"missing-h-extension-discovery",.missing_csr_safety=>"missing-csr-safety",.source_mutated=>"source-mutated",.hgatp_write_attempted=>"hgatp-write-attempted",.active_stage2_forbidden=>"active-stage2-forbidden" }; }
fn actionName(a: HgatpActivationNextAction) []const u8 { return switch(a){ .none=>"none",.build_hgatp_candidate_externally=>"build-hgatp-candidate-externally",.validate_hgatp_candidate_externally=>"validate-hgatp-candidate-externally",.build_stage2_metadata_externally=>"build-stage2-metadata-externally",.build_stage2_table_externally=>"build-stage2-table-externally",.discover_h_extension_externally=>"discover-h-extension-externally",.establish_csr_safety_externally=>"establish-csr-safety-externally",.investigate_source_mutation=>"investigate-source-mutation",.stop_hgatp_write_observed=>"stop-hgatp-write-observed",.stop_active_stage2_observed=>"stop-active-stage2-observed",.future_guarded_write_planning=>"future-guarded-write-planning" }; }
